apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_SERVER_PORT: "8081"
  EUREKA_URL: http://eureka-service.default.svc.cluster.local:8761/eureka
