base-template:
  nameOverride: auth-service
  fullnameOverride: auth-service

  image:
    repository: roin09/auth-service
    tag: latest

  service:
    port: 80
    targetPort: 8081

  env:
    useConfigMap: true
    useSecret: true

  replicaCount: 1

  ingress:
    enabled: 
    host: 

  externalSecret:
    enabled: true
    refreshInterval: 1h
    secretStore:
      name: aws-secrets
      kind: ClusterSecretStore
    dataFromKey: auth-service-secret

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - large

  resources:
    requests:
      cpu: 300m
      memory: 384Mi
    limits:
      cpu: 500m
      memory: 512Mi
