image:
  repository: roin09/auth-service
  tag: latest

service:
  port: 80
  targetPort: 8081

env:
  useConfigMap: true
  useSecret: true

replicaCount: 1

ingress:
  enabled: false

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - large

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
