apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
spec:
  project: default
  source:
    repoURL: https://github.com/GoormPlay/auth-service.git
    targetRevision: deploy
    path: k8s/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
